In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [6]:
url = "https://www.tunyat.com/"
response = requests.get(url)
print(response.status_code)
print(response.url)
print(response.headers)

200
https://www.tunyat.com/
{'content-type': 'text/html; charset=UTF-8', 'link': '<https://static.parastorage.com/>; rel=preconnect; crossorigin, <https://static.parastorage.com/>; rel=preconnect, <https://static.wixstatic.com/>; rel=preconnect; crossorigin, <https://static.wixstatic.com/>; rel=preconnect, <https://siteassets.parastorage.com>; rel=preconnect; crossorigin', 'etag': 'W/"77bc4383564a3e31f528a0b1e1704afa"', 'content-language': 'en-US', 'strict-transport-security': 'max-age=31556952', 'x-cache-status': 'HIT', 'cache-control': 'public,max-age=0,must-revalidate', 'server': 'Pepyaka', 'x-content-type-options': 'nosniff', 'content-encoding': 'gzip', 'accept-ranges': 'bytes', 'age': '295439', 'date': 'Sun, 04 Oct 2026 05:51:58 GMT', 'x-served-by': 'cache-sin-wsat1880070-SIN', 'x-cache': 'HIT', 'vary': 'Accept-Encoding', 'server-timing': 'cache;desc=hit, varnish;desc=hit_hit, dc;desc=fastly_g', 'set-cookie': 'ssr-caching=cache#desc=hit#varnish=hit_hit#dc#desc=fastly_g; max-age=20, sec-fetch-unsupported=1; Path=/; Secure; SameSite=Lax;', 'x-wix-request-id': '1791093118.002694008655213003', 'x-seen-by': 'yvSunuo/8ld62ehjr5B7kA==,xIKq3IotbbLp4+7DTTMx8R9slopJdhD+WySraMrpIY8=,ui2Pjuc3zC1HEw7V2qXeyh9slopJdhD+WySraMrpIY8=,Ua1iSBCTq7qSXjmRCGE1Nzct5yALNpxdk0SYt8KZamt7Tqi0tFUuJitP20zgXuVtiEjJ19gJ6UUN+Su9S15jeO4mbCPDTeKdLVvqK6Ubgfc=,2d58ifebGbosy5xc+FRaluQUM2rwm/Sijv54GVdtGaCeCacmGdPZ6hS9l+Vdsb9fTFpHPsfHRxoVCC1t1goxuA==,2UNV7KOq4oGjA5+PKsX47HqjR+6CNmn/ng3r7CWVjR4=', 'via': '1.1 google', 'glb-x-seen-by': 'bS8wRlGzu0Hc+WrYuHB8QIg44yfcdCMJRkBoQ1h6Vjc=', 'Alt-Svc': 'h3=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'}

In [7]:
print(response.text[:2000])

<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1" id="wixDesktopViewport" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Wix.com Website Builder"/>

  <link rel="icon" sizes="192x192" href="https://static.parastorage.com/client/pfavico.ico" type="image/x-icon"/>
  <link rel="shortcut icon" href="https://static.parastorage.com/client/pfavico.ico" type="image/x-icon"/>
  <link rel="apple-touch-icon" href="https://static.parastorage.com/client/pfavico.ico" type="image/x-icon"/>

  <!-- Safari Pinned Tab Icon -->
  <!-- <link rel="mask-icon" href="https://static.parastorage.com/client/pfavico.ico"> -->

  <!-- Segmenter Polyfill -->
  <script>
    if (!window.Intl || !window.Intl.Segmenter) {
      (function() {
        var script = document.createElement('script');
        script.src = 'https://static.parastorage.com/unpkg/@formatjs/intl-segmenter@11.7.10/polyfill.iife.js';
        document.head.appendChild(script);
      })();
    }
  </script>

  <!-- Legacy Polyfills -->
  <script nomodule="" src="https://static.parastorage.com/unpkg/core-js-bundle@3.2.1/minified.js"></script>
  <script nomodule="" src="https://static.parastorage.com/unpkg/focus-within-polyfill@5.0.9/dist/focus-within-polyfill.js"></script>

  <!-- Performance API Polyfills -->
  <script>
  (function () {
    var noop = function noop() {};
    if ("performance" in window === false) {
      window.performance = {};
    }
    window.performance.mark = performance.mark || noop;
    window.performance.measure = performance.measure || noop;
    if ("now" in window.performance === false) {
      var nowOffset = Date.now();
      if (performance.timing && performance.timing.navigationStart) {
        nowOffset = performance.timing.navigationStart;
      }
      window.performance.now = function now() {
        return Date.now() - nowOffset;
      };
    }
  })();
  </script>

In [8]:
soup = BeautifulSoup(response.text, "html.parser")
print(soup.title)

<title>Tun Yat | Agricultural Service Provider and Social Enterprise in Myanmar</title>

In [9]:
print(soup.title.get_text(strip=True))

Tun Yat | Agricultural Service Provider and Social Enterprise in Myanmar

In [12]:
for child in soup.body.children:
    if child.name:
        print(child.name)

script
script
script
script
script
svg
div
script
script
script
script
script
script
script
script
script
link
link
link
link
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script
script

In [13]:
headings = soup.find_all(["h1", "h2", "h3", "h4"])
print("Number of headings:", len(headings))

for heading in headings:
    print(heading.name, heading.get_text(" ", strip=True))

Number of headings: 4
h4 Save and harvest more Prosperity for all!
h2 Our Story
h2 FOOD DEVELOPMENT
h2 OUR INVESTORS, DONORS AND PARTNERS

In [14]:
heading_data = []
for heading in headings:
    heading_data.append(
        {
            "tag": heading.name,
            "text": heading.get_text("", strip=True)
        }
    )
heading_data

[{'tag': 'h4', 'text': 'Save and harvest moreProsperity for all!'},
 {'tag': 'h2', 'text': 'Our Story'},
 {'tag': 'h2', 'text': 'FOOD DEVELOPMENT'},
 {'tag': 'h2', 'text': 'OUR INVESTORS, DONORS AND PARTNERS'}]

In [15]:
df = pd.DataFrame(heading_data)
df

  tag                                      text
0  h4  Save and harvest moreProsperity for all!
1  h2                                 Our Story
2  h2                          FOOD DEVELOPMENT
3  h2        OUR INVESTORS, DONORS AND PARTNERS

In [16]:
links = soup.find_all("a")
link_data = []

for link in links:
    text = link.get_text("", strip=True)
    href = link.get("href")

    if text or href:
        link_data.append({
            "text": text,
            "url": href
        })
links_df = pd.DataFrame(link_data)
links_df

,text,url
0,,https://www.tunyat.com
1,Home,https://www.tunyat.com
2,About,https://www.tunyat.com/about
3,Our Impact,https://www.tunyat.com/ourimpact
4,Research and Development,https://www.tunyat.com/news
5,Services,https://www.tunyat.com/services
6,Stories,https://www.tunyat.com/stories
7,Highlights,https://www.tunyat.com/stories
8,Shal Kaung Food,https://www.tunyat.com/shalkaung
9,Bake N Bite,https://www.tunyat.com/bnb
10,Contact,https://www.tunyat.com/contact
11,Terms & Conditions,https://www.tunyat.com/terms-conditions
12,,./#comp-kuz3yk84
13,,./#comp-kuz413o0
14,,./#comp-kuz41rnz
15,,./#comp-kuz42is8
16,Read More,https://kr-asia.com/a-data-led-agritech-revolu...
17,Read More,https://marketing-52774.medium.com/a-farmer-a-...
18,Read More,https://www.dls.growasia.org/post/smallholder-...
19,Read More,https://www.sciencedirect.com/science/article/...
20,Button,https://www.tunyat.com/services
21,Button,https://www.tunyat.com/services
22,Button,https://www.tunyat.com/services
23,Visit the Shal Kaung Page,https://www.tunyat.com/shalkaung
24,Visit the Bake N Bite Page,https://www.tunyat.com/bnb
25,SHOP ON FACEBOOK,https://www.facebook.com/shalkaungporridge
26,,https://en.heks.ch/
27,,https://www.uberiscapital.com/
28,,https://www.facebook.com/Daungcapital/
29,,https://www.theyieldlab.com/
30,,https://www.kampani.org/
31,,https://www.babyloan.org/en
32,,https://www.acdivoca.org/
33,,https://www.cpintl.org/
34,,https://we4f.org/
35,,https://www.gsma.com/
36,,https://www.icco-cooperation.org/en/
37,,https://www.worldbank.org/en/home
38,,https://www.deere.com/en/index.html
39,,https://missionlegalmm.com/
40,,http://www.yangondirectory.com/listing/aye-mag...
41,,https://www.facebook.com/bawgamyanmar/community/
42,,https://www.cbbank.com.mm/
43,,https://www.yomabank.com/mm/business
44,,https://www.kubota.com/
45,,https://impacthub.net/
46,,https://www.mosscc.org/
47,Mark,https://www.tunyat.com/terms-conditions
48,,https://www.facebook.com/tunyatagri
49,,https://www.linkedin.com/company/tunyat
50,,https://www.youtube.com/channel/UCj3ARa0NhxVAK...

In [18]:
links_clean = links_df.drop_duplicates()

links_clean

,text,url
0,,https://www.tunyat.com
1,Home,https://www.tunyat.com
2,About,https://www.tunyat.com/about
3,Our Impact,https://www.tunyat.com/ourimpact
4,Research and Development,https://www.tunyat.com/news
5,Services,https://www.tunyat.com/services
6,Stories,https://www.tunyat.com/stories
7,Highlights,https://www.tunyat.com/stories
8,Shal Kaung Food,https://www.tunyat.com/shalkaung
9,Bake N Bite,https://www.tunyat.com/bnb
10,Contact,https://www.tunyat.com/contact
11,Terms & Conditions,https://www.tunyat.com/terms-conditions
12,,./#comp-kuz3yk84
13,,./#comp-kuz413o0
14,,./#comp-kuz41rnz
15,,./#comp-kuz42is8
16,Read More,https://kr-asia.com/a-data-led-agritech-revolu...
17,Read More,https://marketing-52774.medium.com/a-farmer-a-...
18,Read More,https://www.dls.growasia.org/post/smallholder-...
19,Read More,https://www.sciencedirect.com/science/article/...
20,Button,https://www.tunyat.com/services
23,Visit the Shal Kaung Page,https://www.tunyat.com/shalkaung
24,Visit the Bake N Bite Page,https://www.tunyat.com/bnb
25,SHOP ON FACEBOOK,https://www.facebook.com/shalkaungporridge
26,,https://en.heks.ch/
27,,https://www.uberiscapital.com/
28,,https://www.facebook.com/Daungcapital/
29,,https://www.theyieldlab.com/
30,,https://www.kampani.org/
31,,https://www.babyloan.org/en
32,,https://www.acdivoca.org/
33,,https://www.cpintl.org/
34,,https://we4f.org/
35,,https://www.gsma.com/
36,,https://www.icco-cooperation.org/en/
37,,https://www.worldbank.org/en/home
38,,https://www.deere.com/en/index.html
39,,https://missionlegalmm.com/
40,,http://www.yangondirectory.com/listing/aye-mag...
41,,https://www.facebook.com/bawgamyanmar/community/
42,,https://www.cbbank.com.mm/
43,,https://www.yomabank.com/mm/business
44,,https://www.kubota.com/
45,,https://impacthub.net/
46,,https://www.mosscc.org/
47,Mark,https://www.tunyat.com/terms-conditions
48,,https://www.facebook.com/tunyatagri
49,,https://www.linkedin.com/company/tunyat
50,,https://www.youtube.com/channel/UCj3ARa0NhxVAK...

In [19]:
links_unique = (
    links_df[
        links_df["url"].str.startswith(("http://", "https://"), na=False)
    ]
    .drop_duplicates(subset="url")
    .reset_index(drop=True)
)

links_unique

,text,url
0,,https://www.tunyat.com
1,About,https://www.tunyat.com/about
2,Our Impact,https://www.tunyat.com/ourimpact
3,Research and Development,https://www.tunyat.com/news
4,Services,https://www.tunyat.com/services
5,Stories,https://www.tunyat.com/stories
6,Shal Kaung Food,https://www.tunyat.com/shalkaung
7,Bake N Bite,https://www.tunyat.com/bnb
8,Contact,https://www.tunyat.com/contact
9,Terms & Conditions,https://www.tunyat.com/terms-conditions
10,Read More,https://kr-asia.com/a-data-led-agritech-revolu...
11,Read More,https://marketing-52774.medium.com/a-farmer-a-...
12,Read More,https://www.dls.growasia.org/post/smallholder-...
13,Read More,https://www.sciencedirect.com/science/article/...
14,SHOP ON FACEBOOK,https://www.facebook.com/shalkaungporridge
15,,https://en.heks.ch/
16,,https://www.uberiscapital.com/
17,,https://www.facebook.com/Daungcapital/
18,,https://www.theyieldlab.com/
19,,https://www.kampani.org/
20,,https://www.babyloan.org/en
21,,https://www.acdivoca.org/
22,,https://www.cpintl.org/
23,,https://we4f.org/
24,,https://www.gsma.com/
25,,https://www.icco-cooperation.org/en/
26,,https://www.worldbank.org/en/home
27,,https://www.deere.com/en/index.html
28,,https://missionlegalmm.com/
29,,http://www.yangondirectory.com/listing/aye-mag...
30,,https://www.facebook.com/bawgamyanmar/community/
31,,https://www.cbbank.com.mm/
32,,https://www.yomabank.com/mm/business
33,,https://www.kubota.com/
34,,https://impacthub.net/
35,,https://www.mosscc.org/
36,,https://www.facebook.com/tunyatagri
37,,https://www.linkedin.com/company/tunyat
38,,https://www.youtube.com/channel/UCj3ARa0NhxVAK...

In [23]:
internal_links = links_unique[
    links_unique["url"].str.startswith("https://www.tunyat.com")
]

In [24]:
internal_links = internal_links[["text", "url"]].reset_index(drop=True)

internal_links

                       text                                      url
0                                             https://www.tunyat.com
1                     About             https://www.tunyat.com/about
2                Our Impact         https://www.tunyat.com/ourimpact
3  Research and Development              https://www.tunyat.com/news
4                  Services          https://www.tunyat.com/services
5                   Stories           https://www.tunyat.com/stories
6           Shal Kaung Food         https://www.tunyat.com/shalkaung
7               Bake N Bite               https://www.tunyat.com/bnb
8                   Contact           https://www.tunyat.com/contact
9        Terms & Conditions  https://www.tunyat.com/terms-conditions

In [25]:
internal_links.to_csv(
    "tunyat.csv",
    index=False
)